### ISSUE TITLE
Add AddonWorkflow type

### ISSUE THREAD

**Issue by kevdowney** [keikoproj/addon-manager#22]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE
**What happened**:
We want to allow for reusable workflows that can be referenced from addons spec. ex.

```yaml
apiVersion: addonmgr.keikoproj.io/v1alpha1
kind: Addon
metadata:
  name: event-router
  namespace: addon-manager-system
spec:
  pkgName: event-router
  pkgVersion: v0.2
  pkgType: composite
  pkgDescription: "Event router"
  params:
    namespace: addon-event-router-ns
    context:
      clusterName: "kops-aws-usw2.cluster.k8s.local"
      clusterRegion: us-west-2
  lifecycle:
    install:
      template: addon-deployer-helm-wf

    delete:
      template: addon-delete-ns-wf
```

ex. AddonWorkflow type
```yaml
kind: AddonWorkflow
metadata:
  name: addon-deployer-helm-wf
  namespace: addon-manager-system
spec:
...
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Addon Manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- Addon status:
```
$ kubectl describe addon <addon-name>
```
- controller logs:
```
$ kubectl logs <addon-manager-pod>
```
