### ISSUE TITLE
Add pkg* params as injected Workflow params.

### ISSUE THREAD

**Issue by kevdowney** [keikoproj/addon-manager#37]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened**:
We want to the inject `pkg*` spec parameters into the Workflows so they're available as template args inside Workflow.

Add  `pkgParams := addon.Spec.PackageSpec` to line https://github.com/keikoproj/addon-manager/blob/master/pkg/workflows/workflow.go#L104-L106

Then loop and add these parameters as workflow args in same method. 
```go
for name, value := range pkgParams {
  ...
  wfParams = append(wfParams, pkgParam)
}
```
**What you expected to happen**:
We should be able to reference Package params as Workflow template args like so:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  entrypoint: entry
  serviceAccountName: addon-manager-workflow-installer-sa
  templates:
    - name: entry
      steps:
        - - name: install-deployment
            template: submit

    - name: submit
      resource:
        action: apply
        manifest: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: event-router
            namespace: "{{workflow.parameters.namespace}}"
            labels:
              app: event-router
              app.kubernetes.io/version: "{{workflow.parameters.pkgVersion}}"
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Addon Manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- Addon status:
```
$ kubectl describe addon <addon-name>
```
- controller logs:
```
$ kubectl logs <addon-manager-pod>
```
