### ISSUE TITLE
Add error reason message from workflow status

### ISSUE THREAD

**Issue by kevdowney** [keikoproj/addon-manager#44]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened**:
When workflow fails a `status.message` may also be available, be sure to populate Addon `status.reason` w/ failure message in these cases.

```yaml
status:
  finishedAt: "2020-03-17T18:14:35Z"
  message: 'invalid spec: templates.entry.steps[2].wait-prometheus-operator templates.wait-prometheus-operator.resource.action
    must be one of: get, create, apply, delete, replace, patch'
  phase: Failed
  startedAt: "2020-03-17T18:14:35Z"
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Addon Manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- Addon status:
```
$ kubectl describe addon <addon-name>
```
- controller logs:
```
$ kubectl logs <addon-manager-pod>
```
