### ISSUE TITLE
Allow template resources outside of workflows

### ISSUE THREAD

**Issue by kevdowney** [keikoproj/addon-manager#45]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened**:
```
apiVersion: addonmgr.keikoproj.io/v1alpha1
kind: Addon
metadata:
  name: cluster-autoscaler
  namespace: addon-manager-system
spec:
  pkgChannel: cluster-autoscaler
  pkgName: cluster-autoscaler-addon
  pkgVersion: v0.1
  pkgType: composite
  pkgDescription: "cluster-autoscaler"
  params:
    namespace: addon-cluster-autoscaler-ns
    context:
      clusterName: "my-example.cluster.k8s.local"
      clusterRegion: us-west-2
  overrides:
    template: 
      limit-range: |
        apiVersion: v1
        kind: LimitRange
        metadata:
          name: limit-mem-cpu-per-container
        spec:
          limits:
          - max:
              cpu: "800m"
              memory: "1Gi"
            min:
              cpu: "100m"
              memory: "99Mi"
            default:
              cpu: "700m"
              memory: "900Mi"
            defaultRequest:
              cpu: "110m"
              memory: "111Mi"
         type: Container
```
**What you expected to happen**:
Say if you want some extra configuration beyond the template deployer can achieve like adding limitrange, or a resourcequota this should be allowed here.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Addon Manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- Addon status:
```
$ kubectl describe addon <addon-name>
```
- controller logs:
```
$ kubectl logs <addon-manager-pod>
```
