### ISSUE TITLE
Change Argo controller to be deployed by addon-manager and verify it's running.

### ISSUE THREAD

**Issue by kevdowney** [keikoproj/addon-manager#51]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE
**What happened**:
Argo workflow-controller is a central component for addon-manager and needs to be configured correctly.

Improvements:
* Deploy argo using internal deployment or sidecar
* Verify argo is stable and running
* Insert `instanceID: addon-manager-workflow-controller` into Argo configmap
* Add label `workflows.argoproj.io/controller-instanceid: addon-manager-workflow-controller` to all workflows orchestrated by addon-manager
**What you expected to happen**:
Argo configmap.
```
apiVersion: v1
data:
  config: |
    namespace: addon-manager-system
    instanceID: addon-manager-workflow-controller
kind: ConfigMap
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Addon Manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- Addon status:
```
$ kubectl describe addon <addon-name>
```
- controller logs:
```
$ kubectl logs <addon-manager-pod>
```
